In [2]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

# **LOADING DATASET**

In [3]:
! gdown 1fLFm5HSqQYW8_MWihcTky1CQBCUF3pS6
! gdown 1qy-IsjSnZ-Y7qgLXgB_DBN-ZuVf9Lv4Z

Downloading...
From: https://drive.google.com/uc?id=1fLFm5HSqQYW8_MWihcTky1CQBCUF3pS6
To: /content/fear_greed_index.csv
100% 90.8k/90.8k [00:00<00:00, 68.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1qy-IsjSnZ-Y7qgLXgB_DBN-ZuVf9Lv4Z
To: /content/historical_data.csv
100% 47.5M/47.5M [00:00<00:00, 58.9MB/s]

# **DATASET FIRST VIEW**

**Market Sentiment Dataset**

In [4]:
df1 = pd.read_csv('/content/fear_greed_index.csv')
df1.head()

    timestamp  value classification        date
0  1517463000     30           Fear  2018-02-01
1  1517549400     15   Extreme Fear  2018-02-02
2  1517635800     40           Fear  2018-02-03
3  1517722200     24   Extreme Fear  2018-02-04
4  1517808600     11   Extreme Fear  2018-02-05

In [5]:
# Number of rows and columns in the Market Sentiment Dataset.
print("The Rows in the Market Sentiment Dataset = {}".format(df1.shape[0]))
print("The Columns in Market Sentiment Dataset = {}".format(df1.shape[1]))

The Rows in the Market Sentiment Dataset = 2644
The Columns in Market Sentiment Dataset = 4

**Historical Trader Dataset**

In [6]:
df2 = pd.read_csv('/content/historical_data.csv')
df2.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12

In [7]:
# Number of rows and columns in the Historical Trader Dataset.
print("The Rows in Historical Trader Dataset = {}".format(df2.shape[0]))
print("The Columns in Historical Trader Dataset = {}".format(df2.shape[1]))

The Rows in Historical Trader Dataset = 211224
The Columns in Historical Trader Dataset = 16

# **DATASET COLUMNS DESCRIPTION**

**Dataset 1: Market Sentiment**

Column	Description: -

- `timestamp` -	Unix timestamp representing the date of the sentiment value
- `value` -	Numerical Fear & Greed Index (0–100), where lower = fear, higher = greed
- `classification` -	Categorical label derived from index (e.g., Fear, Extreme Fear, Greed)
- `date` -	Human-readable date extracted from timestamp

**Dataset 2: Historical Trader Dataset**

- `Account` -	Unique identifier (wallet address) of the trader
- `Coin` -	Trading pair or asset symbol (e.g., BTC, ETH)
- `Execution Price` -	Price at which the trade was executed
- `Size Tokens` -	Quantity of tokens traded
- `Size USD` -	USD value of the trade
- `Side` -	Trade direction: BUY (long) or SELL (short)
- `Timestamp` -	Unix timestamp (in milliseconds) representing trade time (UTC)
- `Timestamp IST` -	Trade timestamp converted to Indian Standard Time (readable format)
- `Start Position` -	Position size before executing the trade
- `Direction` -	Trade intent (Buy/Sell direction classification)
- `Crossed` -	Boolean indicating whether the trade crossed the order book (taker trade)
- `Closed PnL` -	Profit or loss realized after closing the trade
- `Fee` -	Transaction fee paid for the trade
- `Transaction Hash` -	Unique blockchain transaction identifier
- `Order ID` -	Unique identifier for the order
- `Trade ID` -	Unique identifier for the executed trade

# **DATA PREPROCESSING**

**Data Preprocessing on the Market Sentiment Dataset**

In [27]:
# Copying the Market Sentiment Dataset into the Senti variable
senti = df1.copy()

In [28]:
# Basic information about the Dataset
senti.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       2644 non-null   int64
 1   value           2644 non-null   int64
 2   classification  2644 non-null   object
 3   date            2644 non-null   object
dtypes: int64(2), object(2)
memory usage: 82.8+ KB

In [29]:
# Convert 'date' column to datetime format
senti['date'] = pd.to_datetime(senti['date'], errors='coerce')

In [30]:
senti['classification']=senti['classification'].astype('category')

In [31]:
senti.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       2644 non-null   int64
 1   value           2644 non-null   int64
 2   classification  2644 non-null   category
 3   date            2644 non-null   datetime64[ns]
dtypes: category(1), datetime64[ns](1), int64(2)
memory usage: 64.9 KB

In [32]:
# Checking missing values in dataset
senti.isnull().sum()

timestamp         0
value             0
classification    0
date              0
dtype: int64

In [33]:
# Checking for duplicated values
senti.duplicated().sum()

np.int64(0)

In [34]:
senti.head()

    timestamp  value classification       date
0  1517463000     30           Fear 2018-02-01
1  1517549400     15   Extreme Fear 2018-02-02
2  1517635800     40           Fear 2018-02-03
3  1517722200     24   Extreme Fear 2018-02-04
4  1517808600     11   Extreme Fear 2018-02-05

**Data Preprocessing on the Historical Trader Dataset**

In [35]:
# Copying the Historical Trader Dataset into the trade variable
trade = df2.copy()

In [36]:
# Basic information about the Dataset
trade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211224 non-null  object
 1   Coin              211224 non-null  object
 2   Execution Price   211224 non-null  float64
 3   Size Tokens       211224 non-null  float64
 4   Size USD          211224 non-null  float64
 5   Side              211224 non-null  object
 6   Timestamp IST     211224 non-null  object
 7   Start Position    211224 non-null  float64
 8   Direction         211224 non-null  object
 9   Closed PnL        211224 non-null  float64
 10  Transaction Hash  211224 non-null  object
 11  Order ID          211224 non-null  int64
 12  Crossed           211224 non-null  bool
 13  Fee               211224 non-null  float64
 14  Trade ID          211224 non-null  float64
 15  Timestamp         211224 non-null  float64
dtypes: bool(1), float64(8), int64(1), object(6)
memory usage: 24.4+ MB

In [37]:
# Convert 'Timestamp' to date
trade['date'] = pd.to_datetime(trade['Timestamp'], unit='ms').dt.date
trade['date'] = pd.to_datetime(trade['date'], errors='coerce')

In [38]:
trade[['Account', 'coin', 'side', 'Direction']]=trade[['Account', 'Coin', 'Side', 'Direction']].astype('category')

In [39]:
trade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211224 non-null  category
 1   Coin              211224 non-null  object
 2   Execution Price   211224 non-null  float64
 3   Size Tokens       211224 non-null  float64
 4   Size USD          211224 non-null  float64
 5   Side              211224 non-null  object
 6   Timestamp IST     211224 non-null  object
 7   Start Position    211224 non-null  float64
 8   Direction         211224 non-null  category
 9   Closed PnL        211224 non-null  float64
 10  Transaction Hash  211224 non-null  object
 11  Order ID          211224 non-null  int64
 12  Crossed           211224 non-null  bool
 13  Fee               211224 non-null  float64
 14  Trade ID          211224 non-null  float64
 15  Timestamp         211224 non-null  float64
 16  date              211224 non-null  datetime64[ns]
 17  coin              211224 non-null  category
 18  side              211224 non-null  category
dtypes: bool(1), category(4), datetime64[ns](1), float64(8), int64(1), object(4)
memory usage: 23.8+ MB

In [40]:
# Checking missing values in dataset
trade.isnull().sum()

Account             0
Coin                0
Execution Price     0
Size Tokens         0
Size USD            0
Side                0
Timestamp IST       0
Start Position      0
Direction           0
Closed PnL          0
Transaction Hash    0
Order ID            0
Crossed             0
Fee                 0
Trade ID            0
Timestamp           0
date                0
coin                0
side                0
dtype: int64

In [41]:
# Checking for duplicated values
trade.duplicated().sum()

np.int64(0)

In [42]:
trade.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp,date,coin,side
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12,2024-10-27,@107,BUY
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12,2024-10-27,@107,BUY
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12,2024-10-27,@107,BUY
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12,2024-10-27,@107,BUY
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12,2024-10-27,@107,BUY

# **MERGED DATASET**

In [44]:
# Merging the datasets
merged_df = trade.merge(senti, on='date', how='left')

In [49]:
merged = merged_df[[
    'Account', 'coin', 'Execution Price', 'Size Tokens', 'Size USD', 'Side', 'Start Position', 'Direction', 'Closed PnL', 'Crossed', 'Fee', 'Order ID', 'date', 'value', 'classification'
]]

In [ ]:
merged_df['trade_type'] = merged_df.apply(
    lambda x: 'Open Long' if x['Side']=='BUY' and x['Direction']=='Buy'
    else 'Close Long' if x['Side']=='SELL' and x['Direction']=='Buy'
    else 'Open Short' if x['Side']=='SELL' and x['Direction']=='Sell'
    else 'Close Short',
    axis=1
)

In [51]:
merged.isnull().sum()

Account                0
coin                   0
Execution Price        0
Size Tokens            0
Size USD               0
Side                   0
Start Position         0
Direction              0
Closed PnL             0
Crossed                0
Fee                    0
Order ID               0
date                   0
value              26961
classification     26961
dtype: int64

In [54]:
# Daily PnL per trader (or per account)
daily_pnl=merged.groupby(['Account', 'date'])['Closed PnL'].sum().reset_index()
daily_pnl

                                        Account       date     Closed PnL
0    0x083384f897ee0f19899168e3b1bec365f52a9012 2023-03-28       0.000000
1    0x083384f897ee0f19899168e3b1bec365f52a9012 2023-11-14       0.000000
2    0x083384f897ee0f19899168e3b1bec365f52a9012 2024-03-09       0.000000
3    0x083384f897ee0f19899168e3b1bec365f52a9012 2024-07-03       0.000000
4    0x083384f897ee0f19899168e3b1bec365f52a9012 2024-10-27 -327505.900056
..                                          ...        ...            ...
219  0xbee1707d6b44d4d52bfe19e41f8a828645437aab 2024-03-09       0.000000
220  0xbee1707d6b44d4d52bfe19e41f8a828645437aab 2024-07-03       0.000000
221  0xbee1707d6b44d4d52bfe19e41f8a828645437aab 2024-10-27  684215.002602
222  0xbee1707d6b44d4d52bfe19e41f8a828645437aab 2025-02-19  126967.976166
223  0xbee1707d6b44d4d52bfe19e41f8a828645437aab 2025-06-15   24897.574309

[224 rows x 3 columns]

In [55]:
# win rate
merged['is_win'] = merged['Closed PnL'] > 0
win_rate = merged.groupby('Account')['is_win'].mean() * 100
win_rate.sort_values(ascending=False)

Account
0x75f7eeb85dc639d5e99c78f95393aa9a5f1170d4    81.087638
0xa520ded057a32086c40e7dd6ed4eb8efb82c00e0    57.314149
0x2c229d22b100a7beb69122eed721cee9b24011dd    51.991355
0x4acb90e786d897ecffb614dc822eb231b4ffb9f4    48.622590
0x430f09841d65beb3f27765503d0f850b8bce7713    48.423605
0x3f9a0aadc7f04a7c9d75dc1b5a6ddd6e36486cf6    47.590361
0xbaaaf6571ab7d571043ff1e313a9609a10637864    46.758211
0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891    45.521472
0x7f4f299f74eec87806a830e3caa9afa5f2b9db8f    45.221296
0x23e7a7f8d14b550961925fbfdaa92f5d195ba5bd    44.271978
0xb899e522b5715391ae1d4f137653e7906c5e2115    43.861100
0x28736f43f1e871e6aa8b1148d38d4994275d72c4    43.858463
0x6d6a4b953f202f8df5bed40692e7fd865318264a    43.179487
0xbee1707d6b44d4d52bfe19e41f8a828645437aab    42.823014
0xae5eacaf9c6b9111fd53034a602c192a04e082ed    40.852575
0x513b8629fe877bb581bf244e326a047b249c4ff1    40.119320
0x8170715b3b381dffb7062c0298972d4727a0a63b    38.274288
0x4f93fead39b70a1824f981a54d4e55b278e9f760    36.036392
0x083384f897ee0f19899168e3b1bec365f52a9012    35.961236
0x47add9a56df66b524d5e2c1993a43cde53b6ed85    35.344524
0x72743ae2822edd658c0c50608fd7c5c501b2afbd    34.591195
0xa0feb3725a9335f49874d7cd8eaad6be45b27416    34.578661
0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23    33.713432
0x8381e6d82f1affd39a336e143e081ef7620a3b7f    33.019362
0x39cef799f8b69da1995852eea189df24eb5cae3c    32.766787
0xbd5fead7180a9c139fa51a103cb6a2ce86ddb5c3    32.752745
0xaf40fdc468c30116bd3307bcbf4a451a7ebf1deb    32.209738
0x72c6a4624e1dffa724e6d00d64ceae698af892a0    30.629371
0x271b280974205ca63b716753467d5a371de622ab    30.191651
0x92f17e8d81a944691c10e753af1b1baae1a2cd0d    28.538663
0x8477e447846c758f5a675856001ea72298fd9cb5    26.196826
0x420ab45e0bd8863569a5efbb9c05d91f40624641    23.498695
Name: is_win, dtype: float64

In [59]:
# average trade size per account
avg_trade_size = merged.groupby('Account')['Size USD'].mean()
avg_trade_size.sort_values(ascending=False)

Account
0x513b8629fe877bb581bf244e326a047b249c4ff1    34396.580284
0xb899e522b5715391ae1d4f137653e7906c5e2115    22504.555829
0x4f93fead39b70a1824f981a54d4e55b278e9f760    17098.171055
0x083384f897ee0f19899168e3b1bec365f52a9012    16159.576734
0x4acb90e786d897ecffb614dc822eb231b4ffb9f4     9084.699093
0x271b280974205ca63b716753467d5a371de622ab     8893.000898
0xaf40fdc468c30116bd3307bcbf4a451a7ebf1deb     8330.193371
0xbd5fead7180a9c139fa51a103cb6a2ce86ddb5c3     7852.098338
0x72743ae2822edd658c0c50608fd7c5c501b2afbd     7216.667245
0x8381e6d82f1affd39a336e143e081ef7620a3b7f     6279.002287
0x420ab45e0bd8863569a5efbb9c05d91f40624641     5189.367128
0x39cef799f8b69da1995852eea189df24eb5cae3c     4790.575486
0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23     3837.885375
0x7f4f299f74eec87806a830e3caa9afa5f2b9db8f     3748.867511
0x92f17e8d81a944691c10e753af1b1baae1a2cd0d     3601.689299
0x3f9a0aadc7f04a7c9d75dc1b5a6ddd6e36486cf6     3445.471265
0xbaaaf6571ab7d571043ff1e313a9609a10637864     3210.472831
0x2c229d22b100a7beb69122eed721cee9b24011dd     3138.894782
0xae5eacaf9c6b9111fd53034a602c192a04e082ed     2979.441776
0x75f7eeb85dc639d5e99c78f95393aa9a5f1170d4     2600.778049
0x430f09841d65beb3f27765503d0f850b8bce7713     2397.824753
0x8170715b3b381dffb7062c0298972d4727a0a63b     2204.685531
0x72c6a4624e1dffa724e6d00d64ceae698af892a0     2133.667364
0xa520ded057a32086c40e7dd6ed4eb8efb82c00e0     2066.689209
0xbee1707d6b44d4d52bfe19e41f8a828645437aab     1844.211886
0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891     1729.941104
0x23e7a7f8d14b550961925fbfdaa92f5d195ba5bd     1653.226327
0xa0feb3725a9335f49874d7cd8eaad6be45b27416     1273.195000
0x8477e447846c758f5a675856001ea72298fd9cb5      820.428513
0x6d6a4b953f202f8df5bed40692e7fd865318264a      746.725651
0x47add9a56df66b524d5e2c1993a43cde53b6ed85      517.528924
0x28736f43f1e871e6aa8b1148d38d4994275d72c4      507.626933
Name: Size USD, dtype: float64

In [60]:
# average Trade size per day
avg_trade_size_per_day = merged.groupby('date')['Size USD'].mean()
avg_trade_size_per_day

date
2023-03-28      159.000000
2023-11-14    11057.827522
2024-03-09     5660.265764
2024-07-03     3058.848110
2024-10-27     2949.625864
2025-02-19     5259.977837
2025-06-15    11508.299879
Name: Size USD, dtype: float64

In [61]:
# number of trades per day
trades_per_day = merged.groupby('date').size().reset_index(name='num_trades')
trades_per_day

        date  num_trades
0 2023-03-28           3
1 2023-11-14        1045
2 2024-03-09        6962
3 2024-07-03        7141
4 2024-10-27       35241
5 2025-02-19      133871
6 2025-06-15       26961

In [68]:
# Long_short ratio
long_short=merged.groupby(['date', 'Side']).size().unstack().fillna(0)
long_short['long_short_ratio'] = long_short['BUY'] / (long_short['SELL'] + 1)
long_short.head()

Side            BUY     SELL  long_short_ratio
date
2023-03-28      3.0      0.0          3.000000
2023-11-14    491.0    554.0          0.884685
2024-03-09   3371.0   3591.0          0.938474
2024-07-03   3505.0   3636.0          0.963706
2024-10-27  14927.0  20314.0          0.734777

**Performance vs Sentiment**

In [69]:
# closed PnL vs Sentiment
sentiment_perf = merged_df.groupby('classification')['Closed PnL'].mean()
sentiment_perf

classification
Extreme Fear           NaN
Extreme Greed    25.418772
Fear             50.047622
Greed            87.894859
Neutral          22.229713
Name: Closed PnL, dtype: float64

In [72]:
# win_rate vs sentiment
win_rate_sentiment = merged.groupby('classification')['is_win'].mean()
win_rate_sentiment

classification
Extreme Fear          NaN
Extreme Greed    0.490089
Fear             0.415146
Greed            0.446471
Neutral          0.317182
Name: is_win, dtype: float64

- Traders exhibit lower average PnL and win rates during Fear periods compared to Greed periods.
- This suggests that market uncertainty and panic-driven decisions negatively impact performance.
- In contrast, Greed periods show relatively stable and higher profitability, indicating more favorable trading conditions.

**Behavior Change**

In [76]:
behavior = merged_df.groupby('classification').agg({
    'Size USD': 'mean',
    'Closed PnL': 'mean',
    'Account': 'count'
})
behavior

                   Size USD  Closed PnL  Account
classification
Extreme Fear            NaN         NaN        0
Extreme Greed   5660.265764   25.418772     6962
Fear            5259.977837   50.047622   133871
Greed           3182.883845   87.894859    36289
Neutral         3058.848110   22.229713     7141

During Greed phases, traders tend to:
- Increase trade size
- Take larger positions
- Trade more frequently

During Fear phases, traders:
- Reduce exposure
- Execute smaller trades
- Show more conservative behavior

**Frequent vs Infrequent traders**

In [87]:
trade_counts = merged.groupby('Account').size()
threshold = trade_counts.median()

merged['trader_type'] = merged['Account'].map(
    lambda x: 'Frequent' if trade_counts[x] > threshold else 'Infrequent'
)

merged.groupby('Account')['trader_type'].first()

Account
0x083384f897ee0f19899168e3b1bec365f52a9012      Frequent
0x23e7a7f8d14b550961925fbfdaa92f5d195ba5bd      Frequent
0x271b280974205ca63b716753467d5a371de622ab      Frequent
0x28736f43f1e871e6aa8b1148d38d4994275d72c4      Frequent
0x2c229d22b100a7beb69122eed721cee9b24011dd    Infrequent
0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891    Infrequent
0x39cef799f8b69da1995852eea189df24eb5cae3c    Infrequent
0x3f9a0aadc7f04a7c9d75dc1b5a6ddd6e36486cf6    Infrequent
0x420ab45e0bd8863569a5efbb9c05d91f40624641    Infrequent
0x430f09841d65beb3f27765503d0f850b8bce7713    Infrequent
0x47add9a56df66b524d5e2c1993a43cde53b6ed85      Frequent
0x4acb90e786d897ecffb614dc822eb231b4ffb9f4      Frequent
0x4f93fead39b70a1824f981a54d4e55b278e9f760      Frequent
0x513b8629fe877bb581bf244e326a047b249c4ff1      Frequent
0x6d6a4b953f202f8df5bed40692e7fd865318264a    Infrequent
0x72743ae2822edd658c0c50608fd7c5c501b2afbd    Infrequent
0x72c6a4624e1dffa724e6d00d64ceae698af892a0    Infrequent
0x75f7eeb85dc639d5e99c78f95393aa9a5f1170d4      Frequent
0x7f4f299f74eec87806a830e3caa9afa5f2b9db8f    Infrequent
0x8170715b3b381dffb7062c0298972d4727a0a63b      Frequent
0x8381e6d82f1affd39a336e143e081ef7620a3b7f    Infrequent
0x8477e447846c758f5a675856001ea72298fd9cb5      Frequent
0x92f17e8d81a944691c10e753af1b1baae1a2cd0d    Infrequent
0xa0feb3725a9335f49874d7cd8eaad6be45b27416      Frequent
0xa520ded057a32086c40e7dd6ed4eb8efb82c00e0    Infrequent
0xae5eacaf9c6b9111fd53034a602c192a04e082ed    Infrequent
0xaf40fdc468c30116bd3307bcbf4a451a7ebf1deb    Infrequent
0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23      Frequent
0xb899e522b5715391ae1d4f137653e7906c5e2115      Frequent
0xbaaaf6571ab7d571043ff1e313a9609a10637864      Frequent
0xbd5fead7180a9c139fa51a103cb6a2ce86ddb5c3    Infrequent
0xbee1707d6b44d4d52bfe19e41f8a828645437aab      Frequent
Name: trader_type, dtype: object

consistent winners vs inconsistent traders

In [90]:
total_pnl = merged.groupby('Account')['Closed PnL'].sum()

merged['pnl_type'] = merged['Account'].map(
    lambda x: 'Winner' if total_pnl[x] > 0 else 'Loser'
)
merged.groupby('Account')['pnl_type'].first()

Account
0x083384f897ee0f19899168e3b1bec365f52a9012    Winner
0x23e7a7f8d14b550961925fbfdaa92f5d195ba5bd    Winner
0x271b280974205ca63b716753467d5a371de622ab     Loser
0x28736f43f1e871e6aa8b1148d38d4994275d72c4    Winner
0x2c229d22b100a7beb69122eed721cee9b24011dd    Winner
0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891     Loser
0x39cef799f8b69da1995852eea189df24eb5cae3c    Winner
0x3f9a0aadc7f04a7c9d75dc1b5a6ddd6e36486cf6    Winner
0x420ab45e0bd8863569a5efbb9c05d91f40624641    Winner
0x430f09841d65beb3f27765503d0f850b8bce7713    Winner
0x47add9a56df66b524d5e2c1993a43cde53b6ed85    Winner
0x4acb90e786d897ecffb614dc822eb231b4ffb9f4    Winner
0x4f93fead39b70a1824f981a54d4e55b278e9f760    Winner
0x513b8629fe877bb581bf244e326a047b249c4ff1    Winner
0x6d6a4b953f202f8df5bed40692e7fd865318264a    Winner
0x72743ae2822edd658c0c50608fd7c5c501b2afbd    Winner
0x72c6a4624e1dffa724e6d00d64ceae698af892a0    Winner
0x75f7eeb85dc639d5e99c78f95393aa9a5f1170d4    Winner
0x7f4f299f74eec87806a830e3caa9afa5f2b9db8f    Winner
0x8170715b3b381dffb7062c0298972d4727a0a63b     Loser
0x8381e6d82f1affd39a336e143e081ef7620a3b7f    Winner
0x8477e447846c758f5a675856001ea72298fd9cb5    Winner
0x92f17e8d81a944691c10e753af1b1baae1a2cd0d    Winner
0xa0feb3725a9335f49874d7cd8eaad6be45b27416    Winner
0xa520ded057a32086c40e7dd6ed4eb8efb82c00e0    Winner
0xae5eacaf9c6b9111fd53034a602c192a04e082ed    Winner
0xaf40fdc468c30116bd3307bcbf4a451a7ebf1deb    Winner
0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23    Winner
0xb899e522b5715391ae1d4f137653e7906c5e2115    Winner
0xbaaaf6571ab7d571043ff1e313a9609a10637864    Winner
0xbd5fead7180a9c139fa51a103cb6a2ce86ddb5c3    Winner
0xbee1707d6b44d4d52bfe19e41f8a828645437aab    Winner
Name: pnl_type, dtype: object

# **CONCLUSION**

This analysis demonstrates that market sentiment (Fear vs Greed) has a significant impact on both trader behavior and performance.

During Fear periods, traders tend to adopt a more cautious approach, characterized by reduced position sizes, lower trading activity, and more conservative decision-making. However, despite this caution, performance metrics such as PnL and win rate generally decline, likely due to increased market uncertainty and volatility.

In contrast, Greed periods are associated with increased trading activity, larger trade sizes, and a stronger directional bias toward long positions. These conditions often result in relatively better performance, suggesting that traders benefit from more stable and trend-driven markets.

The analysis also highlights that aggressive trading behavior (e.g., large position sizes or high exposure) leads to higher variability in outcomes, particularly during Fear phases where risk is amplified. Additionally, different trader segments (such as high-frequency vs low-frequency traders) respond differently to sentiment, indicating the importance of adaptive strategies.

Overall, the findings suggest that aligning trading strategies with market sentiment can improve risk-adjusted performance. In particular, adopting a defensive approach during Fear periods and a more opportunistic approach during Greed periods can help traders optimize outcomes while managing risk effectively.